module.exports = {
    "extends": "stylelint-config-standard",
    "ignoreFiles": ["/**/_module.less", "/**/_widgets.less"],
    "rules": {
        "at-rule-empty-line-before": null,
        "no-descending-specificity": false,
        "indentation": null,
        "string-quotes": "single",
        "selector-max-id": null,
        "max-nesting-depth": null,
        "number-leading-zero": "never",
        "max-empty-lines": null,
        "font-family-no-missing-generic-family-keyword": null,
        "no-eol-whitespace": null,
        "color-hex-length": null,
        "block-opening-brace-space-before": null,
        "block-closing-brace-empty-line-before": null,
        "block-closing-brace-newline-after": null,
        "block-no-empty": null,
        "comment-empty-line-before": null,
        "number-leading-zero": null,
        "rule-empty-line-before": null,
        "block-closing-brace-newline-before": null,
        "block-opening-brace-newline-after": null,
        "selector-combinator-space-after": null,
        "declaration-block-no-duplicate-properties": null,
        "selector-combinator-space-after": null,
        "string-quotes": null,
        "no-missing-end-of-source-newline": null,
        "selector-pseudo-element-colon-notation": null,
        "length-zero-no-unit": null,
        "declaration-empty-line-before": null,
        "declaration-colon-space-after": null,
        "declaration-block-trailing-semicolon": null,
        "property-case": null,
        "no-duplicate-selectors": null,
        "declaration-bang-space-before": null,
        "declaration-block-no-shorthand-property-overrides": null,
        "declaration-block-semicolon-newline-after": null,
        "declaration-block-semicolon-space-before": null,
        "comment-whitespace-inside": null,
        "selector-combinator-space-before": null,
        "unit-case": null,
    }
}
